#!/usr/bin/env php

<?php

use Omega\Application\Application;
use Symfony\Component\Console\Application as SymfonyConsoleApplication;

require __DIR__ . '/vendor/autoload.php';

$application = Application::getInstance();
$application->bind('paths.base', fn() => __DIR__);
$application->run();

$console = new SymfonyConsoleApplication();

$commands = require __DIR__ . '/config/console.php';

foreach ($commands as $command) {
    $console->add(new $command);
}

$console->run();
