#!/usr/bin/env php

<?php

use Omega\Application\Application;
use Symfony\Component\Console\Application as ConsoleApplication;

require __DIR__ . '/vendor/autoload.php';

$app = Application::getInstance();
$app->bind('paths.base', fn() => __DIR__);
$app->run();

$console = new ConsoleApplication();

$commands = require __DIR__ . '/config/console.php';

foreach ($commands as $command) {
    $console->add(new $command);
}

$console->run();
